### ISSUE TITLE
Add user to station not working

### ISSUE THREAD

**Issue by Mr-HaleYa** [Mr-HaleYa/mywatersitemisc#3]
https://drive.google.com/file/d/1x6QqgyKR7ilhJ7CAZ0_prPKOCE4IUN7V/view?usp=sharing

**Comment by 0xCTF** [comment]
**fixed**

**Comment by Mr-HaleYa** [comment]
Doesn't appear to be working right 
https://drive.google.com/file/d/1khn9xiUnQUuLZ24WL1tH6e0WYaQrCKq4/view

**Comment by 0xCTF** [comment]
**fixed**

**Comment by Mr-HaleYa** [comment]
Great work

**Comment by Mr-HaleYa** [comment]
Still not working... 

https://drive.google.com/file/d/13xiYM0iifFxjLJ9z9f6wqWhRfXHVfCgJ/view

**Comment by 0xCTF** [comment]
**sorry, it should be fixed now**
